name: NationsTech-SDK-Update

on:
  # schedule:
  #   - cron: "0 2 * * 1-5"
  workflow_dispatch:

env:
  FTP_SERVER: download.nationstech.com
  FTP_USERNAME: anonymous
  FTP_PASSWORD: anonymous

jobs:
  general_mcu:
    name: Sync general MCU SDK
    runs-on: ubuntu-latest

    strategy:
      matrix:
        server_path: [1-Microcontrollers]
        target: 
          - N32G003xx
          # - N32G030xx
          # - N32G031xx
          # - N32G032xx
          # - N32G0V1
          # - N32G401xx
          # - N32G430xx
          # - N32G432xx
          # - N32G435xx
          # - N32G451xx
          # - N32G452xx
          # - N32G455xx
          # - N32G457xx
          # - N32G4FR
          # - N32L40xxx
          # - N32L43xxx
    steps:
    - name: Checkout ${{ matrix.target }}
      uses: actions/checkout@v4
      with:
        repository: NationsTechCoreLib/${{ matrix.target }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run
      run: |
        ls
    - name: Commit files
      run: |
        git config --local user.email "bot@github.com"
        git config --local user.name "bot-action"
        touch ./test
        git add .
        git commit -a -m "Test "
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: NationsTechCoreLib/${{ matrix.target }}
        force_with_lease: true
